"""
This file is a custom implementation of a bounded Spatial Matcher that:
1. Ingests a .txt list of image pairs to compare
    a. These are generated by 'generate_geo_image_pairs.py' based on location proximity
2. Uses COLMAP's matches_importer to feature match the custom list 

"""


import argparse
import subprocess
import sys 

def feature_match(database_path, match_list_path) -> None:

    if database_path is None or not database_path:
        print("Database Path is None. Please provide a valid database path")
        sys.exit(1)

    if ".db" not in str(database_path):
        print("You must provide a path + .db file for the database path -- you did not provide a file at the end of the path -> database.db")
        sys.exit(1)

    if match_list_path is None or not match_list_path:
        print("Images to match file path is None. Please provide a valid match list path")
        sys.exit(1)

    
    if ".txt" not in str(match_list_path):
        print("You must provide a path + .txt file for the match list path -- you did not provide a file at the end of the path -> match_list.txt")
        sys.exit(1)
    
              
    print("Feature matching using Custom [Spatial] Match List")

    print("\nIMPORTANT: If your database has a large number of features, there may be a 5-15 minute delay between COLMAPs first output (e.g., assigning GPU workers) and it actually running")
    print("This is expected, so do not quit the process")

    cmd = [
        "colmap",
        "matches_importer",
        "--database_path", str(database_path),
        "--match_list_path", str(match_list_path),
        "--match_type", "pairs", 
        "--FeatureMatching.use_gpu", "1",  # Use GPU for matching
        "--FeatureMatching.gpu_index", "-1", # Auto-detect GPU
        "--FeatureMatching.num_threads", "-1",  # Detect Automatically the # of threads
        "--FeatureMatching.guided_matching", "1", 
    ]

    try:
        result = subprocess.run(cmd, check=True, text=True)
    except subprocess.CalledProcessError as e:
        print(f"\nFeature matching failed with exit code: {e.returncode}")
        sys.exit(1)

    print("\nFeature matching is done!")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Feature match images using COLMAP matches_importer with spatial match list")
    parser.add_argument(
        "--database_path",
        type=str,
        required=True,
        help="Path to COLMAP database file"
    )
    parser.add_argument(
        "--image_pairs_path",
        type=str,
        required=True,
        help="Path to image pairs matched on GPS distance"
    )

    args = parser.parse_args()

    feature_match(args.database_path, args.image_pairs_path)
